version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
