version: '3.9'
services:
  hypetrain_discordbot:
    image: jumoog/hypetrain_discordbot
    environment:
      - USERID=${USERID}
      - ROOMNAME=${ROOMNAME}
      - CLIENTID=${CLIENTID}
      - CLIENTSECRET=${CLIENTSECRET}
      - DISCORDTOKEN=${DISCORDTOKEN}
      - DEBUGROOMNAME=${DEBUGROOMNAME}
    restart: "always"
    volumes:
      - /home/HypetrainDiscordBot/:/tokens/
